apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-file-upload-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.12, pipelines.kubeflow.org/pipeline_compilation_time: '2022-05-23T12:21:46.411148',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Testing uploading files
      from ui", "inputs": [{"name": "test_data_2", "type": "myBinData"}], "name":
      "Test File Upload"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.12}
spec:
  entrypoint: test-file-upload
  templates:
  - name: test-file-upload
    dag:
      tasks: []
  arguments:
    parameters:
    - {name: test_data_2}
  serviceAccountName: pipeline-runner
