apiVersion: "{apiVersion}"
kind: "InferenceService"
metadata:
  name: "{modelName}"
  namespace: "{modelNamespace}"
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  predictor:
    tensorflow:
      storageUri: "pvc://{volumeResourceName}/"