apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "{serviceName}"
  namespace: "{modelNamespace}"
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  predictor:
    pytorch:
      storageUri: "pvc://{volumeResourceName}/{experimentName}"
      env: [
        {
          name: "random_seed",
          value: "{randomSeed}" # This will prevent kserve from reusing the revision
        }
      ]