apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "serve-mnist"
  namespace: "{modelNamespace}"
spec:
  predictor:
    pytorch:
      storageUri: "gs://kfserving-examples/models/torchserve/image_classifier"