apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "{modelName}"
  namespace: "{modelNamespace}"
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  predictor:
    pytorch:
      storageUri: "pvc://{volumeResourceName}/{experimentName}/outputs/{datasetName}"